dependencies:
- alabaster=0.7.6=py34_0
- babel=2.1.1=py34_0
- backports_abc=0.4=py34_0
- cycler=0.9.0=py34_0
- decorator=4.0.4=py34_0
- docutils=0.12=py34_0
- freetype=2.5.5=0
- ipykernel=4.1.1=py34_0
- ipython=4.0.0=py34_0
- ipython-notebook=4.0.4=py34_0
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_0
- jsonschema=2.4.0=py34_0
- jupyter_client=4.1.1=py34_0
- jupyter_core=4.0.6=py34_0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- llvmlite=0.8.0=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.5.0=np110py34_0
- mistune=0.7.1=py34_0
- nbconvert=4.0.0=py34_0
- nbformat=4.0.1=py34_0
- nose=1.3.7=py34_0
- notebook=4.0.6=py34_0
- numba=0.22.1=np110py34_0
- numexpr=2.6.0=np110py34_0
- numpy=1.10.1=py34_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- pandas=0.18.1=np110py34_0
- path.py=8.1.2=py34_1
- patsy=0.4.0=np110py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- ptyprocess=0.5=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_0
- python=3.4.3=2
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- pyzmq=14.7.0=py34_1
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.0=np110py34_1
- setuptools=18.5=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.8.4.1=1
- statsmodels=0.6.1=np110py34_0
- terminado=0.5=py34_1
- tk=8.5.18=0
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - cloud-sptheme==1.7
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - sphinx-rtd-theme==0.1.7

